version: "3.8"

services:

  postgres:
    container_name: survivor_db
    image: postgres:14.2
    environment:
      POSTGRES_DB: survivor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - survivor-postgres:/var/lib/postgresql/data


  survivor:
    container_name: survivor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    read_only: false
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

  app-migrations:
    container_name: survivor-migrations
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file: .env
    read_only: false
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/setup-db.sh

volumes:
  survivor-postgres:
  app:
